// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7p10YplVtO7pf6dShsPtvNMnhSncAdHY',
    appId: '1:339984881057:web:a6a9e4b6a16b06dfea27e0',
    messagingSenderId: '339984881057',
    projectId: 'gava-a0d3a',
    authDomain: 'gava-a0d3a.firebaseapp.com',
    storageBucket: 'gava-a0d3a.appspot.com',
    measurementId: 'G-723K9QWNRD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvxcCKiuV1AinevIuC3tvXv2TfcvILtIk',
    appId: '1:339984881057:android:da2673b0fe43b674ea27e0',
    messagingSenderId: '339984881057',
    projectId: 'gava-a0d3a',
    storageBucket: 'gava-a0d3a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRWr-k5nfkCtadL5VtEK2iVUbaFo8SEU0',
    appId: '1:339984881057:ios:b0bfcb0911a354f3ea27e0',
    messagingSenderId: '339984881057',
    projectId: 'gava-a0d3a',
    storageBucket: 'gava-a0d3a.appspot.com',
    iosBundleId: 'com.jungjoo.gava',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRWr-k5nfkCtadL5VtEK2iVUbaFo8SEU0',
    appId: '1:339984881057:ios:312067b38d587c1dea27e0',
    messagingSenderId: '339984881057',
    projectId: 'gava-a0d3a',
    storageBucket: 'gava-a0d3a.appspot.com',
    iosBundleId: 'com.jungjoo.gava.RunnerTests',
  );
}
